### ISSUE TITLE
Can't "show" the toc

### ISSUE THREAD

**Issue by jabarig** [HareInWeed/pdf-toc#2]
I tried to show the toc using your example
`pdf-toc --show-toc file.pdf`

but I get this error message
`pdf-toc: error: argument --show-toc: invalid choice: 'file.pdf' (choose from 'json', 'toc')`

What am I doing wrong?

**Comment by HareInWeed** [comment]
I forgot to update the example section in REAME.md. `--show-toc` must be passed along with an output format now. The command 

```
pdf-toc --show-toc file.pdf
```

should be 

```
pdf-toc --show-toc toc file.pdf
```

or `pdf-toc --show-toc json file.pdf` if you prefer json format

**Comment by jabarig** [comment]
Thanks!
